// import type { NextPage } from 'next';
// import Head from 'next/head';
// import { useState } from 'react';
// import { prisma } from '../../lib/prisma';
// import { GetServerSideProps } from 'next';
// import { useRouter } from 'next/router';
// import { useForm } from './hook';
// import type { brand, iot as IotType } from "@prisma/client";
// import IotTable from './table'
// import IotFomr from './form'
// const  return (
//     <div className='bg-black'>
//       <Head>
//         <title>Asset Iot</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

      
//     </div>
//   );

// export default Cobi;

// export const getServerSideProps: GetServerSideProps = async () => {
//   const iots = await prisma?.iot.findMany({
//     select: {
//       id: true,
//       devname: true,
//       devid: true,
//       devtype: true,
//       deveui: true,
//       brandId: true,
//       brand: true,
//     },
//   });

//   const brands = await prisma?.brand.findMany({
//     select: {
//       id: true,
//       name: true,
//       bid: true,
//     },
//   });

//   const noBrands = brands.length === 0;

//   return {
//     props: {
//       brands: brands || [],
//       noBrands: noBrands,
//       iot: iots || [],
//     },
//   };
// };
